EmployeeCreateInput:
  type: input-object
  config:
    fields:
      name:
        type: "String!"
        description: "Name of an employee"
      salary:
        type: "Int!"
        description: "Salary of an employee"
      age:
        type: "Int!"
        description: "Age of an employee"