version: '3.7'
services:
  mysql:
    container_name: dummy-mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dummy 
  php:
   build:
     context: .
     dockerfile: docker/php/Dockerfile
   container_name: dummy-php
   volumes:
     - "./app/:/usr/src/app"
   environment:
     DATABASE_URL: mysql://root:root@mysql:3306/dummy?serverVersion=8.0
  nginx:
    container_name: dummy-nginx
    image: nginx:1.15.3
    volumes:
      - "./app/:/usr/src/app"
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - "80:80"
    depends_on:
     - php