security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
    
    providers:
        backend_users:
            memory:
                users:
                    admin: { password: 'admin', roles: ['ROLE_API_USER'] }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: "^/api/employees"
            provider: backend_users
            http_basic:
                realm: "Api"
        api_graphiql:
            pattern: "^/graphiql"
            provider: backend_users
            http_basic:
                realm: "Api"
        api_graphql:
            pattern: "^/g"
            provider: backend_users
            http_basic:
                realm: "Api"

    access_control:
        - { path: ^/api/employees, roles: ROLE_API_USER }
        - { path: ^/graphiql, roles: ROLE_API_USER }
        - { path: ^/g, roles: ROLE_API_USER }